### PR TITLE
Fix math imports; drop Math

### PR DESCRIPTION
**Pull request by JordanMartinez**
**Description of the change**

Drops `math`; updates imports

---

**Checklist:**

- [x] Added the change to the changelog's "Unreleased" section with a link to this PR and your username
- [ ] Linked any existing issues or proposals that this pull request should close
- [ ] Updated or added relevant documentation in the README and/or documentation directory
- [ ] Added a test for the contribution (if applicable)

### CODE REVIEW

**Comment by thomashoneyman** [comment]
Bit of an interesting CI error here.

**Comment by JordanMartinez** [comment]
Huh... Yeah it is. I'll look into it.

**Comment by JordanMartinez** [comment]
The failing test is caused by Nate's changes in `purescript-parsing`, specifically `choice`: https://github.com/purescript-contrib/purescript-parsing/commit/f50e8dd01d09d619a837e502b0c82d5d84a82844#diff-d472726f9da7dc968f3c6ef534ba99b06228789ab00a1f2dfe04eebfde42ffc6L445-R445

Changing this line (https://github.com/purescript-contrib/purescript-formatters/blob/main/src/Data/Formatter/Parser/Interval.purs#L32=) to the following makes the test pass again:
```diff
- parseInterval duration date = [ startEnd, durationEnd, startDuration, durationOnly ] <#> PC.try # 
+ parseInterval duration date = [ startEnd, durationEnd, startDuration, durationOnly ] <#> PC.try # foldl (<|>) empty
```
Conceptually, the parse is the same. The difference is what the final parser is and how that affects the error message:
```
-- choice == foldr (<|>) empty
a <|> b <|> c <|> empty

-- choice == foldl (<|>) empty
empty <|> a <|> b <|> c
```
@natefaubion I believe you modified `choice` because `<|>` hadn't yet been made right-associative. Now that it is, should `choice` be reverted back to `foldl (<|>) empty`?

**Comment by natefaubion** [comment]
I think choice should still be right associative. The fact that choice required you to always step through a useless alternative is crazy.

**Comment by JordanMartinez** [comment]
K, I'll update the error message then.

**Comment by JordanMartinez** [comment]
Can I get an approval?

**Comment by natefaubion** [comment]
Sorry, I'm not saying that the current error behavior is OK, I'm just saying that I would like to preserve both. I'll need to think about it.

**Review by thomashoneyman — APPROVED** [review]

**Pull request merged**
