### PR TITLE
Update to v0.14.0-rc3

### PR DESCRIPTION
**Pull request by JordanMartinez**
Backlinking to purescript-contrib/governance#35

### CODE REVIEW

**Comment by JordanMartinez** [comment]
This still won't build because it relies on Spec. It'll take a bit more work to update completely.

**Comment by JordanMartinez** [comment]
This should pass now, but it uses `MonadZero`'s `guard`. What should that function be replaced with now?

**Comment by garyb** [comment]
There's an `Alternative`-constrained `guard` now that should work I think?

**Comment by JordanMartinez** [comment]
Yup, that works. I've updated this PR.

**Comment by thomashoneyman** [comment]
Could we add the dependency changes to the changelog?

**Comment by JordanMartinez** [comment]
How's that? Or did you mean something more than that?

**Comment by JordanMartinez** [comment]
I'm actually not sure that `numbers` is needed as it's likely pulled in via a transitive dependency

**Review by thomashoneyman — APPROVED** [review]

**Pull request merged**
