### PR TITLE
Fix warnings revealed by PureScript v0.14.1

### PR DESCRIPTION
**Pull request by PureFunctor**
**Description of the change**
Links to purescript-contrib/governance#37

---

**Checklist:**

- [x] Added the change to the changelog's "Unreleased" section with a link to this PR and your username
- [ ] Linked any existing issues or proposals that this pull request should close
- [ ] Updated or added relevant documentation in the README and/or documentation directory
- [ ] Added a test for the contribution (if applicable)

### CODE REVIEW

**Comment by PureFunctor** [comment]
Not entirely sure what to do with:
https://github.com/purescript-contrib/purescript-formatters/blob/6347c2c50b78445f0a10ed2496fddbdf4e3d382a/test/src/DateTime.purs#L200-L201
Should this be removed or exported?

**Review by JordanMartinez — APPROVED** [review]

**Comment by JordanMartinez** [comment]
What does `git blame` show for that? If it's not being used, it was likely there when someone was debugging the code or something. I'm leaning towards removing it.

**Comment by natefaubion** [comment]
It should be removed.

**Comment by PureFunctor** [comment]
> What does `git blame` show for that? If it's not being used, it was likely there when someone was debugging the code or something. I'm leaning towards removing it.

It points to (a squashed) #17; that seems to be the case though so I went ahead and removed it

**Pull request merged**
